version: '3.7'

services:
  bertopic:
    container_name: bertopic
    build: .
    command: bash -c 'while !</dev/tcp/minio/9000; do sleep 1; done; uvicorn service.main:app --host 0.0.0.0'
    ports:
      - 8008:8000
    env_file:
      ./.env
    volumes:
      - .:/app
    depends_on:
      - minio
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/${MINIO_BUCKET_NAME} && /opt/bin/minio server --console-address ":9001" /data'
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      ./.env
    volumes:
      - data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data: