version: '3.7'

services:
  bertopic:
    container_name: bertopic
    image: bertopic-as-service:latest
    build: .
    command: >
      bash -c "
      while !</dev/tcp/minio/9000; do echo 'Wait minio to startup...' && sleep 1; done;
      uvicorn service.main:app --host 0.0.0.0"
    ports:
      - 8008:8000
    environment:
      MINIO_URL: http://minio:9000
      MINIO_REGION_NAME: berttopic
      MINIO_BUCKET_NAME: default_bucket
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: bertopic
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - minio
      - db

  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:latest
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/${MINIO_BUCKET_NAME};
      /opt/bin/minio server --console-address ':9001' /data"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_REGION_NAME: berttopic
      MINIO_BUCKET_NAME: default_bucket
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    container_name: mc
    image: quay.io/minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: >
      /bin/sh -c "
      while !</dev/tcp/minio/9000; do echo 'Wait minio to startup...' && sleep 1; done;
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin user add myminio ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc admin policy set myminio readwrite user=${MINIO_ACCESS_KEY};
      exit 0;"
    depends_on:
      - minio

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_DB: bertopic
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - pg_data:/var/lib/postgresql/data
    

volumes:
  data:
  pg_data: