kind: Service
apiVersion: v1
metadata:
  name: minio-service
  namespace: bertopic
spec:
  selector:
    app: minio-container
  ports:
    - name: api-port
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console-port
      protocol: TCP
      port: 9001
      targetPort: 9001
