apiVersion: v1
kind: Service
metadata:
  name: bertopic-service
  namespace: bertopic
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
