kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: bertopic
  labels:
    type: local
    app: backend
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pg15_bertopic
    type: DirectoryOrCreate

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube # <-- name of the node (docker-desktop, minikube) etc.
