name: build

on:
  pull_request:
    branches:
    - "**"
  push:
    branches:
    - main

env:
  MINIO_URL: http://minio:9000
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_REGION_NAME: berttopic
  MINIO_BUCKET_NAME: default_bucket
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: bertopic
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  REGISTRY: ghcr.io
  IMAGE: shkaolin/bertopic-as-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: $REGISTRY
          image_name: $IMAGE:cache
          push_image_and_stages: false