name: build

on:
  pull_request:
    branches:
    - "**"
  push:
    branches:
    - main

env:
  MINIO_URL: http://minio:9000
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_REGION_NAME: berttopic
  MINIO_BUCKET_NAME: default_bucket
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build images
      run: |
        make build

    - name: Start services
      run: |
        make up

    - name: Run code checks
      run: |
        docker-compose run --rm --no-deps bertopic make check-code

    - name: Run integration tests
      run: |
        make test