name: build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

env:
  MINIO_HOST: minio
  MINIO_PORT: 9000
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_REGION_NAME: berttopic
  MINIO_BUCKET_NAME: default_bucket
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: bertopic
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  REGISTRY: ghcr.io
  IMAGE_NAME: shkaolin/bertopic-as-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build --cache-from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -t bertopic-as-service:latest --build-arg BUILDKIT_INLINE_CACHE=1 .

      - name: Start services
        run: |
          make up-dev

      - name: Run code checks
        run: |
          docker-compose run --rm --no-deps bertopic make check-code

      - name: Run integration tests
        run: |
          make test

      - name: Push image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag bertopic-as-service:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Send telegram message on merging to master
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🎉 master brach is updated, congratulations!

            *Repository*: ${{ github.repository }}

            *See changes*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
