name: build

on:
  pull_request:
    branches:
    - "**"
  push:
    branches:
    - main

env:
  MINIO_URL: http://minio:9000
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_REGION_NAME: berttopic
  MINIO_BUCKET_NAME: default_bucket
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  DOCKER_BUILDKIT: 1
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: bertopic
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  REGISTRY: ghcr.io
  IMAGE_NAME: shkaolin/bertopic-as-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start services
        run: |
          docker-compose up -d --no-build --scale bertopic=0

      - name: Run code checks
        run: |
          docker-compose run --rm --no-deps bertopic make check-code

      - name: Run integration tests
        run: |
          make test

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
